
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: mass_shifter_joint
  pid: {p: 10000, i: 0.1, d: 100}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: irm1_joint
  pid: {p: 100, i: 0.001, d: 0.05}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: irm2_joint
  pid: {p: 100, i: 0.001, d: 0.05}
